//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerPointLaTeX.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class MiKTexSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MiKTexSettings defaultInstance = ((MiKTexSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MiKTexSettings())));
        
        public static MiKTexSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DistributionPath {
            get {
                return ((string)(this["DistributionPath"]));
            }
            set {
                this["DistributionPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LatexFilename {
            get {
                return ((string)(this["LatexFilename"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DVIPNGFilename {
            get {
                return ((string)(this["DVIPNGFilename"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LatexPath {
            get {
                return ((string)(this["LatexPath"]));
            }
            set {
                this["LatexPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DVIPNGPath {
            get {
                return ((string)(this["DVIPNGPath"]));
            }
            set {
                this["DVIPNGPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MikTexTemplate {
            get {
                return ((string)(this["MikTexTemplate"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DistributionType {
            get {
                return ((string)(this["DistributionType"]));
            }
            set {
                this["DistributionType"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("miktex\\bin")]
        public string MikTexBinPath {
            get {
                return ((string)(this["MikTexBinPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2012\\bin\\win32")]
        public string TexLiveBinPath {
            get {
                return ((string)(this["TexLiveBinPath"]));
            }
        }
    }
}
